# name: Auto comment on Push

# on: 
#   push: 
#     branches:
#       - maind

# jobs:
#   comment_on_commit:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Prepare and post JSON comment
#         run: |
#           COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments"

#           # Define your JSON data
#           JSON_COMMENT=$(cat <<EOF
# {
#   "component": {
#     "key": "mesh-api-Temp",
#     "name": "mesh-api-Temp",
#     "qualifier": "TRK",
#     "measures": [
#       {
#         "metric": "alert_status",
#         "value": "OK"
#       }
#     ]
#   }
# }
# EOF
# )

#           # Escape JSON string to be safely posted in the GitHub comment
#           ESCAPED_JSON=$(echo "$JSON_COMMENT" | jq -Rs .)

#           # Post the comment to the latest commit
#           curl -L -X POST \
#             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#             -H "Content-Type: application/json" \
#             -d "{\"body\": ${ESCAPED_JSON}" \
#             "$COMMENT_URL"
